---
version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: on-failure:10


  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    ports:
      # To learn about configuring Kafka for access across networks see
      # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    restart: on-failure:10


  kafdrop:
    image: obsidiandynamics/kafdrop:4.0.0-SNAPSHOT
    depends_on:
      - kafka
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"

  #  grafana:
  #    image: grafana/grafana:8.5.22-ubuntu
  #    depends_on:
  #      - kafka
  #    ports:
  #      - "3000:3000"
  #    environment:
  #      GF_INSTALL_PLUGINS: "hamedkarbasi93-kafka-datasource"


  influxdb:
    image: influxdb:2.7.0
    volumes:
      # Mount for influxdb data directory and configuration
      - ./mounts/influxdbv2:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"

  influxdb-init:
    image: influxdb:2.7.0
    links:
      - influxdb
    entrypoint: /bin/bash /etc/influxdb/configs/config.sh
    restart: on-failure:10
    depends_on:
      - influxdb
    volumes:
      - ./configs/influxdb:/etc/influxdb/configs:ro
      - ./mounts/influxdbv2:/var/lib/influxdb2:rw

  telegraf:
    image: telegraf:1.26.1
    depends_on:
      - influxdb
    volumes:
      # Mount for telegraf config
      - ./configs/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro